name: "Auto Release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions: write-all
    name: "Build & Release"
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: "Build with Maven"
        run: mvn -B package --file pom.xml

      - name: "Make a New Release"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            target/*.jar